name: Deploy to Azure App Service

env:
  AZURE_WEBAPP_NAME: tarik-tasktopr-01
  AZURE_WEBAPP_PACKAGE_PATH: "."
  AZURE_REGISTRY_SERVER: tariktasktopr01.azurecr.io
  DOTNET_VERSION: "7.0.x"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://${{ env.AZURE_REGISTRY_SERVER }}
          username: ${{ secrets.AzureAppService_ContainerUsername }}
          password: ${{ secrets.AzureAppService_ContainerPassword }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.AZURE_REGISTRY_SERVER }}/${{ secrets.AzureAppService_ContainerUsername }}/tarik:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          images: "${{ env.AZURE_REGISTRY_SERVER }}/${{ secrets.AzureAppService_ContainerUsername }}/tarik:${{ github.sha }}"
